image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals.
# https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: python3 -m http.server
    
# List the ports you want to expose and what to do when they are served.
# https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

# Enable prebuilds of your project to enable faster workspace start times.
# https://www.gitpod.io/docs/prebuilds/#configure-the-github-app
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true